version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: lawyerconnect_db
    restart: always
    environment:
      MYSQL_DATABASE: lawyer_Connect
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: lawyerconnect_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./BackEnd/lawyerConnect_backend
      dockerfile: Dockerfile
    container_name: lawyerconnect_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/lawyer_Connect?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
      - redis

  frontend:
    image: nginx:alpine
    container_name: lawyerconnect_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./FrontEnd:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  mysql_data:
